t:
  ua:
    About: 'Про конкурс'
    Conditions: 'Умови конкурсу'
    Programm: 'Програма'
    Prizes: 'Премії та нагороди'
    Jury: 'Журі'
    Partners: 'Партнери'
    Contacs: 'Контакти'
  en:
    About: 'About'
    Conditions: 'Conditions'
    Programm: 'Programm'
    Prizes: 'Prizes'
    Jury: 'Jury'
    Partners: 'Partners'
    Contacs: 'Contacs'
  # ru:
    # Language: 'Язык'


